name: release

on:
  repository_dispatch:
  workflow_dispatch:
#  push:
#    branches:
#      - 'v2'
#    tags:
#      - 'v*'
#  pull_request:
#    branches:
#      - 'v2'

jobs:
  release:
    strategy:
      matrix:
        platform: [ubuntu-latest]
        go-version: [1.17]
    name: Release
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: v2
          path: alist
          persist-credentials: false
          fetch-depth: 0

      - name: Set up xgo
        run: |
          docker pull techknowlogick/xgo:latest
          go install src.techknowlogick.com/xgo@latest
          sudo apt install upx

      - name: Build
        run: |
          git clone -b dist https://github.com/xopenwrt/alist-web.git
          mv alist-web/* alist/public
          mv alist/build.sh .
          bash build.sh release

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: alist/build/compress/*